import React from 'react'
import styles from './style.css'

const Privacy = () => {
  return (
    <div className={styles.privacy}>
      <div className={styles.container}>
        <h1 className={styles.title}>Satoshi's Fury Privacy Policy</h1>
        <p className={styles.lastUpdated}>Last updated: November 27, 2025</p>
        
        <p className={styles.intro}>
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className={styles.intro}>
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <section className={styles.section}>
          <h2>Interpretation and Definitions</h2>
          
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company," "We," "Us," or "Our" in this Agreement) refers to Satoshi's Fury Project Entity/Operator.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Cayman Islands</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Satoshi's Fury Platform, the system that allows users to submit contract trading loss/liquidation screenshots and receive token compensation.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Collecting and Using Your Personal Data</h2>
          
          <h3>Types of Data Collected</h3>
          
          <h4>Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>Wallet Address</li>
            <li>Email Address (Used for registration or verification)</li>
            <li>Social Media Account ID or Handle (Used for registration or verification)</li>
            <li>Submission Content: Including the contract trading loss/liquidation screenshots and associated trade verification information that You upload.</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
          </p>

          <h4>Information from Third-Party Social Media Services</h4>
          <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
          <ul>
            <li>Google</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>Twitter</li>
            <li>Telegram</li>
          </ul>
          <p>
            If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal Data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities, or Your contact list associated with that account.
          </p>

          <h4>Tracking Technologies and Cookies</h4>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul>
            <li><strong>Necessary / Essential Cookies:</strong> To provide You with services available through the Website and enable You to use some of its features.</li>
            <li><strong>Cookies Policy / Notice Acceptance Cookies:</strong> To identify if users have accepted the use of cookies on the Website.</li>
            <li><strong>Functionality Cookies:</strong> To allow us to remember choices You make when You use the Website.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> The development, compliance, and undertaking of any contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services, and events which we offer.</li>
            <li><strong>To manage Your requests:</strong> To attend to and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> To evaluate or conduct a merger, divestiture, restructuring, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, and to evaluate and improve our Service. Specifically, for the verification and processing of your submitted contract trading loss evidence to determine airdrop eligibility.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Sharing of Your Personal Data</h2>
          <p>We may share Your personal information in the following situations:</p>
          <ul>
            <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service, or to contact You.</li>
            <li><strong>For business transfers:</strong> In connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, who will be required to honor this Privacy Policy.</li>
            <li><strong>With business partners:</strong> To offer You certain products, services, or promotions.</li>
            <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Retention, Transfer, and Deletion of Your Personal Data</h2>
          
          <h3>Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
          </p>

          <h3>Transfer of Your Personal Data</h3>
          <p>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. By consenting to this Privacy Policy, You agree to such transfer.
          </p>

          <h3>Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Disclosure of Your Personal Data</h2>
          <ul>
            <li><strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred.</li>
            <li><strong>Law enforcement:</strong> The Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
            <li><strong>Other legal requirements:</strong> The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing in connection with the Service, protect the personal safety of Users of the Service or the public, and protect against legal liability.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>Security of Your Personal Data</h2>
          <p>
            We strive to use commercially acceptable means to protect Your Personal Data, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. We cannot guarantee its absolute security.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Children's Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top.
          </p>
        </section>

        <section className={styles.section}>
          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: <a href="mailto:support@satoshisfury.com">support@satoshisfury.com</a></li>
          </ul>
        </section>
      </div>
    </div>
  )
}

export default Privacy

